### PR TITLE
Add prettier pre-push hook

### PR DESCRIPTION
**Pull request by JustusFT**

### CODE REVIEW

**Comment by donpui** [comment]
@JustusFT can we add description from OP ticket here?

**Comment by donpui** [comment]
What is the working flow here? Dev makes a change (for example he doesn't use any formatting in VScode or any other tool) and push changes. On push event lint (prettier --check) will run and give output (warning/errors or all ok). Will it push anyway, or it will reject push till formatting will be fixed. 
Also there is command `npm run format`, which is not run automatically. So if there are warning, should dev then run npm run format and then push changes again?

**Comment by JustusFT** [comment]
@donpui
When the user sets up the environment with `npm i`, a git hook gets installed that runs the script in `.husky/pre-push`. This script runs when the user tries to push. If `prettier --check` fails then the user is told to run `prettier --write` or `npm run format` before trying to push again

**Comment by donpui** [comment]
> @donpui When the user sets up the environment with `npm i`, a git hook gets installed that runs the script in `.husky/pre-push`. This script runs when the user tries to push. If `prettier --check` fails then it will reject and the user is told to run `prettier --write` or `npm run format` before trying to push again

Clear. Can we add this description in README.md, for development process? So CI action would help us here only in those cases, if still someone is pushing without formatting, then we could see failure in Github.

**Review by donpui — CHANGES_REQUESTED** [review]
Lets add documentation in README.md and it will be good to go

**Comment by meejah** [comment]
This is a good approach; notemyou can still push with `git push --force` and bypass the checks.

It's important to remember that these hooks are to _help_ the developer, not hinder them. Sometimes you do want to push things that aren't "done" (including formatting). For example, you're about to travel or want some feedback on in-progress branches.

(The only place you really _don't_ want to push un-formatted code is to `main` so that's where PR checks help).

**Review by donpui — APPROVED** [review]

**Pull request merged**
