### PR TITLE
Add cache-control for resources

### PR DESCRIPTION
**Pull request by donpui**
As we are not using any CDN, lets add some cache-control for static resource management, to speed up a little bit of Winden.app resources

### CODE REVIEW

**Comment by donpui** [comment]
It works on stage.winden.app

**Comment by wuan** [comment]
Regarding the caching of code I have seen the following pattern in the past: Cached code elements use a filename which contains a hash value derived from the content, e. g. `main_2c0bfa304ad5010b49a8ee9d76fe39d8.js`. The only file which is not cached is the central `index.html`.

This has the advantage, that you can cache code (JavaScript and WASM) indefinitely while still having the possibility to perform an update which will roll out to all users as fast as possible.

I assume that this would require updating the way we build our application, but it might be useful.

**Review by wuan — APPROVED** [review]
LGTM, only question I have: What happens when we update js/wasm? Is the change propagating immediately or do we need to wait until the data expires?

**Comment by meejah** [comment]
> What happens when we update js/wasm? Is the change propagating immediately or do we need to wait until the data expires?

From a quick scan I believe a user will have to wait at least 1 day to see the change (unless they e.g. "`ctrl-shift-R`" in Firefox to force a re-load). I think @wuan's first suggestion is good here -- so maybe we should turn off caching on JS until that (or similar) is implemented?

I believe webpack does this by default, but I don't know how we're packaging JS.

**Comment by donpui** [comment]
> > What happens when we update js/wasm? Is the change propagating immediately or do we need to wait until the data expires?
> 
> From a quick scan I believe a user will have to wait at least 1 day to see the change (unless they e.g. "`ctrl-shift-R`" in Firefox to force a re-load). I think @wuan's first suggestion is good here -- so maybe we should turn off caching on JS until that (or similar) is implemented?
> 
> I believe webpack does this by default, but I don't know how we're packaging JS.

We use gulp, but I see there are some webpack stuff too. However we don't have hash filename for wasm or js put in place. Maybe we can do that? https://www.npmjs.com/package/gulp-hash-filename  @JustusFT what is your opinion here?

**Comment by JustusFT** [comment]
We may be able to automatically hash the wasm file if we can use a webpack loader to build it (maybe [this](https://github.com/aaronpowell/webpack-golang-wasm-async-loader)?). Otherwise we can use `gulp-hash-filename` as long as we have a way to keep the [fetch statement](https://github.com/LeastAuthority/winden/blob/main/client/src/worker/index.ts#L23) updated as well

**Comment by donpui** [comment]
I will update cache-control to remove js and wasm till find option to generate them with hash filenames

**Comment by donpui** [comment]
For further improvement, this task: https://github.com/LeastAuthority/winden/issues/65

**Pull request merged**
