### PR TITLE
Enable Code Scanning

### PR DESCRIPTION
**Pull request by donpui**
Enabling CodeQL analysis engine for Javascript/Typescript. It is integrated in Github and recommended.

More about tool:
https://codeql.github.com/docs/codeql-overview/

Javascript/Typescript specific issues checklist:
https://github.com/github/codeql/tree/codeql-cli/latest/javascript/ql/src

Results are visible in: https://github.com/LeastAuthority/winden/security/code-scanning

### CODE REVIEW

**Comment by meejah** [comment]
Is there a ticket describing why we want this and what it does? (That link is pretty low on details, I still don't understand what we get here).

**Comment by donpui** [comment]
> Is there a ticket describing why we want this and what it does? (That link is pretty low on details, I still don't understand what we get here).

I don't have a ticket here. Just jump on this option, checking other things in github. Maybe worth to register issue on engineering repo for common discussion and enabling not only here.

As for CodeQL so it check for various language specific coding error. 
https://github.com/github/codeql/tree/codeql-cli/latest
What exactly it check for Javascript/Typescript we can find in repo, for example as we use React, so it will for such kind of things:
https://github.com/github/codeql/blob/codeql-cli/latest/javascript/ql/src/React/examples/UnusedOrUndefinedStateProperty.js

Currently our code is quite good and no issues are found, however, never know, when something can popup. Actually I am try to insert something, to see if it is catching at all :)

**Comment by meejah** [comment]
I've had mixed results with these sorts of tools.

That said, I'm definitely not opposed to experimenting, but I still don't understand what we really get here ;) -- but, okay, I don't need to understand that: if it starts being more annoyance than benefit we can delete it then.

**Comment by meejah** [comment]
(And on the plus side, if it's happy with our code _now_ then we aren't causing work immediately)

**Pull request merged**
