### PR TITLE
Add external link icons

### PR DESCRIPTION
**Pull request by JustusFT**
OP#2286

### CODE REVIEW

**Comment by donpui** [comment]
Can we do anything about size? As it seems now we add 0.5mb for downloading tabler-icons.woff2, also whole tabler-icons.min.css which 112 kb.

**Comment by JustusFT** [comment]
We can look into tree-shaking the css or lazy loading it: OP#2276

**Comment by wuan** [comment]
I'm not a huge fan of pulling binaries into a repo which exist outside. Could we offload that into our build process. If we want to ensure to be able to build even without internet we could think about adding these via Git LFS.

**Comment by donpui** [comment]
@JustusFT is it possible to extract only that particular icon and incorporate it without all these additional fonts, resources. Just to try keep application as minimal as possible?

**Comment by JustusFT** [comment]
@donpui That's possible if I convert the plain html files to react components: #72

**Pull request closed without merging**
