### PR TITLE
Integration tests retry

### PR DESCRIPTION
**Pull request by donpui**
Sometimes integration tests failed in Github Action, manual retry usually helped that. 

Lets try with automatic retry for jest

### CODE REVIEW

**Review by JustusFT — APPROVED** [review]
Looks like the commit from #84 is also in this pr. Should be ok as long as that gets merged first

**Comment by donpui** [comment]
> Looks like the commit from #84 is also in this pr. Should be ok as long as that gets merged first

Yes, my mistake, created another branch not from main. I will merge sequentially

**Comment by meejah** [comment]
Won't this just hide the real problem?

Now we either won't see a real problem that happens once (because it'll automatically retry) or when the particular problem that retry "solves" happens nobody will look at it either.

**Comment by donpui** [comment]
> 

No, it will not. Retry will happen once. if there is real issue, retry will not help. Currently when we commit and pull request, two the same tests are running. Usually one completes fully, another time to time fails on some tests due to timeout. This is not constant failure, but only on Github Actions. Manual rerun action usually passes. I tried to investigate Githug, but it takes to much time to debug real cause. Most like it is related with all resource available as we fire up a lot of docker containers on Github virtual machine

**Comment by meejah** [comment]
Yes it will, though: whatever problem is only "sometimes" happening will be hidden, at least.

Any other similar "not always repeatable" problem will also be silently hidden, because it'll be immediately retried.

Also it means that there's way less reason to fix the GHA (or whatever) issue, so that will just "never" be fixed, approximately.

Is there even a ticket describing the actual problem?

**Comment by exarkun** [comment]
Intermittently failing CI is always annoying and feels like a waste of time and the temptation to do *something* to get it reliably green is pretty understandable.  However, it's worth keeping the goal of all this work in mind to help guide the kind of fixes that we choose to apply.  If the goal is to build software that works reliably then getting failures from the test suite is exactly what we want.  It's better if they're deterministic, of course, but even if they're non-deterministic or otherwise intermittent they still represent *the whole value* of the test suite.  A test suite that cannot fail is absolutely worthless because it cannot tell us anything about the software.  An automatic retry in the CI configuration that takes an intermittent test failure that happens 10% of the time and makes it happen 1% of the time has reduced the value of that test by a factor of 10.  And a retry that covers a whole test module (or maybe the whole test suite?  I'm not familiar with `jest` and I don't know how broad the impact of the change here is)  potentially does this many, many tests.  That's may be a catastrophic loss of value.

If the goal is to build software without regard for whether it works reliably then there is an easier way to drive the failure rate to 0 - just delete the test suite.  If reliability isn't the goal then the test suite is almost a pure cost and may as well be skipped.  I doubt this is the goal, though, so I would urge reconsideration of this strategy.

Maybe it will take a lot of tedious, careful debugging to make the test suite pass reliably.  Maybe some architectural decisions will even have to be reconsidered.  Maybe some kind of retry is actually exactly what's called for (if CI fetches some resource over the network, for example, that's a good thing to have retry logic around because networks are unreliable, especially on CI).  But the PR doesn't mention what test fails or how it fails so I don't know.  Also, anyone who wants to look into the reliability of the test suite in the future will presumably have at least as hard of a time figuring out what the motivation was here.  So I *also* suggest full details of the problem being addressed here get written down - maybe in the PR description, maybe in a new issue describing a work task to *remove* this retry logic and replace it with a better fix.

**Comment by donpui** [comment]
Thanks for suggestion. We can have an issue for reviewing all tests execution and going away from retries.

**Pull request merged**
