### PR TITLE
Use WebAssembly.instantiate for now

### PR DESCRIPTION
**Pull request by JustusFT**
#26

### CODE REVIEW

**Review by donpui — APPROVED** [review]

**Comment by wuan** [comment]
After the response from OVH support we have a solution to fix the problem on the Apache Webserver level. (see https://github.com/LeastAuthority/winden/issues/26#issuecomment-1255021399)

**Comment by wuan** [comment]
What we still would need to do is add that `.htaccess` file to the distribution folder as a step in the build.

**Comment by JustusFT** [comment]
Now that the `.htaccess` is added (#31), do we still need this `WebAssembly.instantiate` workaround?

**Comment by donpui** [comment]
> Now that the `.htaccess` is added (#31), do we still need this `WebAssembly.instantiate` workaround?

I think now, but fallback option should be always.

**Pull request closed without merging**
