### PR TITLE
Enable indexing in robots.txt

### PR DESCRIPTION
**Pull request by donpui**
Enabling robots.txt to allow robots to crawl over our content for production environment. 

Related with SEO optimisation task: #OP 2324

### CODE REVIEW

**Comment by wuan** [comment]
The added file `robots.prod.txt` gets added to the stage deployment:
image
Maybe it is better to update `robots.txt` during the deployment via
```
sed -i "" 's/Disallow:/Allow:/g' robots.txt
```
or even generate it from the deployment script.

**Comment by donpui** [comment]
> The added file `robots.prod.txt` gets added to the stage deployment: image Maybe it is better to update `robots.txt` during the deployment via
> 
> ```
> sed -i "" 's/Disallow:/Allow:/g' robots.txt
> ```
> 
> or even generate it from the deployment script.

Yes, maybe. I will check, as now we are very much dependent from github actions

**Comment by donpui** [comment]
Moved to gulpfile.js solution. @JustusFT take a look, maybe we can have even better approach, as now I needed to add two new packages.

**Review by wuan — APPROVED** [review]
Looks good for me.

**Pull request merged**
