### PR TITLE
Port worker tests from `Transfer` repo

### PR DESCRIPTION
**Pull request by JustusFT**
OP#1927

### CODE REVIEW

**Comment by donpui** [comment]
How do we run tests in Transfer-rewrite? may be we can add some info to Readme?

**Comment by JustusFT** [comment]
It's already in the [readme](https://github.com/LeastAuthority/Transfer-rewrite#running-tests)

```
# run tests once
docker-compose run client npm run test
# or automatically re-run tests when editing a file
docker-compose run client npm run test -- --watch
```

**Comment by donpui** [comment]
Please add information, how to watch go changes.

**Comment by JustusFT** [comment]
@donpui made a PR for that: https://github.com/LeastAuthority/Transfer-rewrite/pull/15

**Review by donpui — APPROVED** [review]

**Comment by donpui** [comment]
I have tested, it works for me. @vu3rdd would you like to take a look, then we don't need to use Transfer for wasm testing.

**Review by vu3rdd — APPROVED** [review]

**Comment by donpui** [comment]
@JustusFT can you check why failing test unit and intergration tests?

**Comment by JustusFT** [comment]
> @JustusFT can you check why failing test unit and intergration tests?

@donpui It works fine locally, not sure why the CI is getting `EOF` when trying to transfer the test files

**Pull request merged**
