### PR TITLE
Add feedback api form

### PR DESCRIPTION
**Pull request by JustusFT**
Ref: https://github.com/LeastAuthority/winden/issues/118

Adds the new feedback form on the front-end. The form will make a post request to `/v1/feedback` on submit.

### CODE REVIEW

**Comment by donpui** [comment]
Few initial notes:
1. Allows to submit empty form. Maybe require at least one field had some value, doesn't matter which.
2. Maybe notification "Feedback sent" could be hidden after 10 sec. as now it is always visible till user clicks
3. "On a scale" line has larger font and weight, was this intentionally done (like encourage to rate)?
4. Lets add simple E2E test to fill form and send.

**Comment by JustusFT** [comment]
I'll add non-empty validation

---

I was thinking about auto-hiding the notification, but I think it's better if it's manually closed or that it closes on it's own after navigating to a different screen. That way the user can't miss the message (if they miss it, they might try to submit the same feedback again)

Some other options we can do:
- keep the alert section where it is now, but it closes itself after ~10s or navigating to a new page
- A modal saying that the feedback was sent (most in-the-way approach, but the user can't miss it)
- use a floating notification like https://mantine.dev/others/notifications/#demo (but the bottom-right area is be easy to miss)

---

I'm just using the default theme for now, just pushed to code as is to check if there is any changes we want to do before I start on that

---

Will do :+1:

**Comment by donpui** [comment]
Few small notes:
- Can we keep the same notification style, when user gets error filling form, with success, only make different notification icon. Currently error is shown in bottom and it is not fully clear if it is an error.
- Currently we don't limit length, how much user can input. Maybe each field could limit text to maximum 2000 symbols.

**Comment by JustusFT** [comment]
> Can we keep the same notification style, when user gets error filling form, with success, only make different notification icon. Currently error is shown in bottom and it is not fully clear if it is an error.

I haven't worked on the styling and layout of it yet, I wanted to get the tests green first. Though I think it should stay near the bottom in the same style as the form validation for the code input: red text under the fields. Since it applies to all fields, I think it should be near the Submit button. wdyt?

**Comment by donpui** [comment]
> I haven't worked on the styling and layout of it yet, I wanted to get the tests green first. Though I think it should stay near the bottom in the same style as the form validation for the code input: red text under the fields. Since it applies to all fields, I think it should be near the Submit button. wdyt?

Logical, as you don't need to look top if page doesn't reload.

**Comment by JustusFT** [comment]
@donpui I added content size validation and changed the styling

**Review by donpui — APPROVED** [review]
LGTM. Additionally made small changes for feedback-api to sync output: https://github.com/LeastAuthority/feedback-api/pull/16

**Pull request merged**
