### PR TITLE
Avoid duplicate and useless checks

### PR DESCRIPTION
**Pull request by btlogy**
As described in #94, we  may want to avoid the integration test to run twice upon pull_request.

This PR introduce a pre-check to avoid duplicate test to be run on the same content.
In addition, this PR also provides:
- a manual trigger to test any branch w/o having to create a PR.
- a similar pre-check to skip code analysis based on the same criteria
- new file, workflow and job names to improve clarity 

---

## Code Review Checklist (to be filled out by reviewer)

- [ ] Description accurately reflects what changes are being made.
- [ ] Description explains why the changes are being made (or references an issue containing one).
- [ ] The PR appropriately sized.
- [ ] New code has enough tests. 
- [ ] New code has enough documentation to answer "how do I use it?" and "what does it do?".
- [ ] Existing documentation is up-to-date, if impacted.

### CODE REVIEW

**Comment by btlogy** [comment]
I've not found any existing documentation of our use of GitHub actions in this repository.
Therefore, I'm not planning to update or create any in relation to this PR.

**Comment by btlogy** [comment]
Looking at the check results attached to this PR, it seems like the test has been run only once as requested.

**Comment by donpui** [comment]
Please confirm if I correctly understand:
- main.yml CI will run on any pull_request to any branch
- main.yml CI will run only on push to main branch (in reality we are not directly pushing to main).

If so, then it is fine by me (we will need probably apply the same in few other repos: destiny, w-w)

**Comment by btlogy** [comment]
>     * main.yml CI will run on any pull_request to any branch
>     * main.yml CI will run only on push to main branch (in reality we are not directly pushing to main).
That is my understanding indeed.
And also that merging a pull_request is triggering a push event on main branch.

What might no longer work after this PR is the automatic run of the test when somebody pushes more commits in a pull_request that is already open.
And for that matter, I hope the manual trigger could help.

> If so, then it is fine by me (we will need probably apply the same in few other repos: destiny, w-w)
That might depends on who the actions are organized in those repositories. We do not seem to have a standard approach.
For instance, in some case there is one action file to cover many jobs (i.e.: build, test and deploy), and it might be more tricky to filter the events then.

Let see how it works for this case first.

**Comment by btlogy** [comment]
@donpui, let's merge this PR once you'll have ticked (or not) the check-boxes in the description.
And see if the test is triggered in the main branch after the merge.
Though, I suspect we should check if this happens again for the next PR too.

**Comment by donpui** [comment]
> What might no longer work after this PR is the automatic run of the test when somebody pushes more commits in a pull_request that is already open.
> And for that matter, I hope the manual trigger could help.

That part might not be good, as we tend to push new commits/changes after review on PR. Manual actions depends too much depend on people and there is risk that we can merge something unverified.

May be this can help: 
https://github.com/marketplace/actions/skip-duplicate-actions

**Comment by btlogy** [comment]
> > What might no longer work after this PR is the automatic run of the test when somebody pushes more commits in a pull_request that is already open.
> > And for that matter, I hope the manual trigger could help.
> 
> That part might not be good, as we tend to push new commits/changes after review on PR. Manual actions depends too much depend on people and there is risk that we can merge something unverified.
> 
> May be this can help: https://github.com/marketplace/actions/skip-duplicate-actions

I'm testing different options in a sandbox repository (la-test/sbx-actions#27).
I'll propose some change here later...

**Comment by btlogy** [comment]
As suggested by @donpui, the use of skip-duplicate-actions seems to achieve our goal here (and likely in other repositories too).
I've tested as much as I could (in [sbx-actions](https://github.com/la-test/sbx-actions)), but I think this PR will have to be merged first before we can verify its full impact.

**Comment by btlogy** [comment]
@donpui : can you have a second look here and tick the check-boxes in the description?

**Review by donpui — APPROVED** [review]

**Pull request merged**
